name: Typescript
description: Run Typescript check

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: TypeScript
      run: npx tsc --noEmit --emitDeclarationOnly false
      shell: bash
