name: License validator
description: Run license validator check

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build license validator
      run: npm run build:license-validator
      shell: bash

    - name: Run license validator
      run: |
        chmod +x ./.license-validator -R
        npm run check-license
      shell: bash
