name: Publish to Firefox Add-ons

on:
  workflow_dispatch:

jobs:
  publish-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install publish-browser-extension
        run: pnpm install -g publish-browser-extension

      - name: Download Firefox build artifact
        uses: actions/download-artifact@v4
        with:
          name: cloudhood-firefox
          path: dist/firefox
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.run_id || github.run_id }}

      - name: Download Firefox sources artifact
        uses: actions/download-artifact@v4
        with:
          name: cloudhood-firefox-sources
          path: dist/firefox-sources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.run_id || github.run_id }}

      - name: Upload to Firefox Add-ons
        env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
        run: |
          npx publish-extension \
            --firefox-zip dist/firefox/cloudhood-firefox.zip \
            --firefox-sources-zip dist/firefox-sources/cloudhood-firefox-sources.zip \
            --firefox-extension-id ${{ env.FIREFOX_EXTENSION_ID }} \
            --firefox-jwt-issuer ${{ env.FIREFOX_JWT_ISSUER }} \
            --firefox-jwt-secret ${{ env.FIREFOX_JWT_SECRET }}
