name: Publish to Chrome Web Store

on:
  workflow_dispatch:

jobs:
  publish-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install publish-browser-extension
        run: pnpm install -g publish-browser-extension

      - name: Download Chrome build artifact
        uses: actions/download-artifact@v4
        with:
          name: cloudhood-chrome
          path: dist/chrome
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.run_id || github.run_id }}

      - name: Upload to Chrome Web Store
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          CHROME_PUBLISH_TARGET: ${{ secrets.CHROME_PUBLISH_TARGET }}
        run: |
          npx publish-extension \
            --chrome-zip dist/chrome/cloudhood-chrome.zip \
            --chrome-extension-id ${{ env.CHROME_EXTENSION_ID }} \
            --chrome-client-id ${{ env.CHROME_CLIENT_ID }} \
            --chrome-client-secret ${{ env.CHROME_CLIENT_SECRET }} \
            --chrome-refresh-token ${{ env.CHROME_REFRESH_TOKEN }} \
            --chrome-publish-target ${{ env.CHROME_PUBLISH_TARGET }}
